arch: arm64
os: linux
dist: xenial
language: python

services:
  - docker

before_install:
  - docker build -t krajnishk/compose_flask -f Dockerfile .

script:
  - docker run krajnishk/compose_flask echo hello world

